all:
  hosts:
#    dev:
#      ansible_port: 22
#      ansible_host: dev.rocksea.co.kr
#      ansible_user: ubuntu
#      ansible_ssh_private_key_file: /Users/rocksea/bin/rocksea-dev.pem
#      #ansible_python_interpreter: /home/ubuntu/.pyenv/shims/python
#    stage:
#      ansible_port: 22
#      ansible_host: stage.rocksea.co.kr
#      ansible_user: ubuntu
#      ansible_ssh_private_key_file: /Users/rocksea/bin/rocksea-stage.pem
#      #ansible_python_interpreter: /home/ubuntu/.pyenv/shims/python
#    production:
#      ansible_port: 22
#      ansible_host: production.rocksea.co.kr
#      ansible_user: ubuntu
#      ansible_ssh_private_key_file: /Users/rocksea/bin/rocksea-real.pem
#      #ansible_python_interpreter: /Users/rocksea/.pyenv/shims/python
