- hosts: localhost
  vars:
    server_name: rocksea
    server_port: 80
    project_name: rocksea
    pyenv_root: /usr/local/bin/
    python_ver: 3.8.5
    jenv_root: /usr/local/bin/
    java_version: 17
    go_version: 1.17.1
    node_version: 16.19.0
    terraform_version: 1.0.7
    nginx_conf_dir: /etc/nginx/sites-available
    nginx_sites_dir: /etc/nginx/sites-enabled
    nginx_error_log: /var/log/nginx
  tasks:
  - include: homebrew/setup.yml
  - include: vim/setup.yml
  - include: zsh/setup.yml
  - include: java/setup.yml
  - include: python/setup.yml
  - include: go/setup.yml
  - include: k8s/setup.yml
  - include: aws/setup.yml
  - include: terraform/setup.yml
