- hosts: localhost
  vars:
    server_name: rocksea
    server_port: 80
    project_name: rocksea
    pyenv_root: /usr/local/bin/
    python_ver: 3.8.5
    jenv_root: /usr/local/bin/
    java_ver: 11
    nginx_conf_dir: /etc/nginx/sites-available
    nginx_sites_dir: /etc/nginx/sites-enabled
    nginx_error_log: /var/log/nginx
  tasks:
  - include: homebrew/setup.yml
  - include: vim/setup.yml
  - include: zsh/setup.yml
  - include: java/setup.yml
  - include: python/setup.yml
  - include: k8s/setup.yml
