- name: Install Jenv
  shell: |
    brew install jenv

- name: Add an openjdk tap
  shell: |
    brew tap homebrew/cask-versions

- name: Install Java11
  shell: |
    brew install --cask temurin11

- name: Install Java17
  shell: |
    brew install --cask temurin17

- name: Install Gradle
  shell: |
    brew install gradle

- name: Install Maven
  shell: |
    brew install maven

- name: Set up Java Environments
  shell: |
    echo 'export JENV_ROOT="$HOME/.jenv"' >> ~/.zshrc
    echo 'export PATH="$JENV_ROOT/bin:$PATH"' >> ~/.zshrc
    echo 'eval "$(jenv init -)"' >> ~/.zshrc
    . ~/.zshrc
    {{ jenv_root }}jenv add /Library/Java/JavaVirtualMachines/adoptopenjdk-{{ java_version }}.jdk/Contents/Home
    {{ jenv_root }}jenv global {{ java_version }}
  ignore_errors: True
