- name: Installing a Helm
  shell: |
    brew install helm
  ignore_errors: True

- name: Installing a Eksclt
  shell: |
    brew install eksctl
  ignore_errors: True

- name: Installing a Kubectl
  shell: |
    brew install kubectl
  ignore_errors: True

- name: Installing a Argocd CLI
  shell: |
    brew install argocd
  ignore_errors: True

- name: Installing a Argo rollouts
  shell: |
    brew install argoproj/tap/kubectl-argo-rollouts
  ignore_errors: True

- name: Installing a Kustomize
  shell: |
    curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
  ignore_errors: True

- name: Installing a istioctl
  shell: |
    curl -L https://istio.io/downloadIstio | sh -
    cd istio*
    chmod +x ./bin/istioctl
    sudo mv ./bin/istioctl /usr/local/bin
  ignore_errors: True
