- name: Installing zsh
  shell: |
    brew install zsh

- name: Installing oh-my-zsh
  shell: |
    /bin/sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    cp zsh/zshrc ~/.zshrc
